#!/usr/bin/env python3

import argparse
import json
import os
import subprocess

parser = argparse.ArgumentParser()
parser.add_argument("--json", type=json.loads, required=True, help="the json input")

args, unknown = parser.parse_known_args()

collection_name = args.json["collection"]["name"]
topic_path = args.json["topic"]["path"]
topic_basename = os.path.basename(topic_path)
top_k = args.json["top_k"]

out_file_name = args.json["opts"]["out_file_name"]
search_args = args.json["opts"]["search_args"]

subprocess.run("""
    java -cp anserini.jar io.anserini.search.SearchCollection
        -topicreader Trec
        -index {} -topics {} -hits {}
        -output /output/{}
        {}
""".format(collection_name, topic_path, top_k, out_file_name, search_args).split())
